[versions]
kotlin                  = "2.2.20"
compose-multiplatform   = "1.11.0"
agp                     = "8.8.0"

android-compileSdk      = "35"
android-minSdk          = "24"
android-targetSdk       = "35"

androidx-activityCompose = "1.9.3"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }

[plugins]
kotlin-multiplatform    = { id = "org.jetbrains.kotlin.multiplatform",  version.ref = "kotlin" }
compose-multiplatform   = { id = "org.jetbrains.compose",               version.ref = "compose-multiplatform" }
compose-compiler        = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application     = { id = "com.android.application",             version.ref = "agp" }
